import { Inter } from "next/font/google"
import "./globals.css"
import SessionProviderWrapper from "./SessionProviderWrapper" // adjust path if in /components

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  )
}
